const date = new Date();
let hours = date.getHours();
const minutes = date.getMinutes().toString().padStart(2, "0");
const ampm = hours >= 12 ? "PM" : "AM";
hours = hours % 12 || 12;
const formattedTime = `${hours}:${minutes} ${ampm}`;
const formattedDate = `${date.getDate()} ${date.toLocaleString("en-US", {
  month: "long",
})}, ${date.getFullYear()}`;

const chatList = [
  {
    id: 1,
    Name: "Sunrise International School",
    pic: "/superadmin.png",
    messages: [
      {
        sender: "Parent",
        receiver: "School",
        text: "Hello! When does the new term start?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Good day! The new term starts on the 15th of September.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "When will we receive the school fee invoice?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Invoices will be sent via email next week.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Great! What about uniforms?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Uniforms are available at the school store.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Is there a discount for early payment?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes! 5% off for payments made before September 1st.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Thank you! I'll process payment soon.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "You're welcome! Let us know if you need help.",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 2,
    isActive: true,
  },
  {
    id: 2,
    Name: "Bright Future Academy",
    pic: "/female.png",
    messages: [
      {
        sender: "Parent",
        receiver: "School",
        text: "Good afternoon. When is the PTA meeting?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Next Friday at 4 PM.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Will it be online or physical?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "It will be held in the school hall.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "What topics will be discussed?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Academic performance, school policies, and extracurriculars.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Great! Can we bring students along?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "This session is for parents only.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Understood. Thank you!",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "You're welcome!",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 1,
    isActive: true,
  },
  {
    id: 3,
    Name: "Royal Crest School",
    pic: "/superadmin.png",
    messages: [
      {
        sender: "Student",
        receiver: "School",
        text: "When will exam results be released?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Results will be available by Monday.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Will there be a corrections period?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Yes, students can request corrections until next Friday.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Where do we submit correction requests?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Submit them to your class teacher.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Got it! Thanks!",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "You're welcome!",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Will there be an awards ceremony?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Yes! Date will be announced soon.",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 3,
    isActive: true,
  },
  {
    id: 4,
    Name: "Greenwood High",
    pic: "/female.png",
    messages: [
      {
        sender: "Parent",
        receiver: "School",
        text: "Is the school bus available for new students?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes! Registration is open at the admin office.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "What is the cost?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Fees depend on the distance from school.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Can we choose pickup locations?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes, as long as they are on the school route.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Okay. Is there a discount for multiple children?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes, a 10% discount for siblings.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "That’s great! I’ll register soon.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Looking forward to it!",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 2,
    isActive: true,
  },
  {
    id: 1,
    Name: "Sunrise International School",
    pic: "/superadmin.png",
    messages: [
      {
        sender: "Parent",
        receiver: "School",
        text: "Hello! When does the new term start?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Good day! The new term starts on the 15th of September.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "When will we receive the school fee invoice?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Invoices will be sent via email next week.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Great! What about uniforms?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Uniforms are available at the school store.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Is there a discount for early payment?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes! 5% off for payments made before September 1st.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Thank you! I'll process payment soon.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "You're welcome! Let us know if you need help.",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 2,
    isActive: true,
  },
  {
    id: 2,
    Name: "Bright Future Academy",
    pic: "/female.png",
    messages: [
      {
        sender: "Parent",
        receiver: "School",
        text: "Good afternoon. When is the PTA meeting?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Next Friday at 4 PM.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Will it be online or physical?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "It will be held in the school hall.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "What topics will be discussed?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Academic performance, school policies, and extracurriculars.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Great! Can we bring students along?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "This session is for parents only.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Understood. Thank you!",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "You're welcome!",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 1,
    isActive: true,
  },
  {
    id: 3,
    Name: "Royal Crest School",
    pic: "/superadmin.png",
    messages: [
      {
        sender: "Student",
        receiver: "School",
        text: "When will exam results be released?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Results will be available by Monday.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Will there be a corrections period?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Yes, students can request corrections until next Friday.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Where do we submit correction requests?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Submit them to your class teacher.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Got it! Thanks!",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "You're welcome!",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Student",
        receiver: "School",
        text: "Will there be an awards ceremony?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Student",
        text: "Yes! Date will be announced soon.",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 3,
    isActive: true,
  },
  {
    id: 4,
    Name: "Greenwood High",
    pic: "/female.png",
    messages: [
      {
        sender: "Parent",
        receiver: "School",
        text: "Is the school bus available for new students?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes! Registration is open at the admin office.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "What is the cost?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Fees depend on the distance from school.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Can we choose pickup locations?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes, as long as they are on the school route.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "Okay. Is there a discount for multiple children?",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Yes, a 10% discount for siblings.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "Parent",
        receiver: "School",
        text: "That’s great! I’ll register soon.",
        date: formattedDate,
        time: formattedTime,
      },
      {
        sender: "School",
        receiver: "Parent",
        text: "Looking forward to it!",
        date: formattedDate,
        time: formattedTime,
      },
    ],
    unread: 2,
    isActive: true,
  },
];

export default chatList;
