const compliance = [
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
  {
    SchoolName: "Peace International College",
    TaxCompliance: "Uploaded",
    AccreditionDoc: "Uploaded",
    ProofOfReg: "Unuploaded",
    UploadedOn: "22/03/2025",
  },
];
export default compliance;
