const dummyUsers = [
  {
    userId: "USR001",
    schoolid: "SCH001",
    pin: "1234",
    username: "Ife Babalola Adesina",
    password: "password",
    Role: "Student",
    profilePic: "/female.png",
  },
  {
    userId: "USR002",
    schoolid: "SCH002",
    pin: "5678",
    username: "Jane Smith",
    password: "password",
    Role: "Teacher",
    profilePic: "/profile.png",
  },
  {
    userId: "USR003",
    schoolid: "SCH003",
    pin: "9012",
    username: "Bob Johnson",
    password: "password",
    Role: "Student",
    profilePic: "/profile.png",
  },
  {
    userId: "USR004",
    schoolid: "SCH004",
    pin: "3456",
    username: "Mary Lee",
    password: "password",
    Role: "Student",
    profilePic: "/profile.png",
  },
  {
    userId: "USR005",
    schoolid: "SCH005",
    pin: "7890",
    username: "Tom Brown",
    password: "password",
    Role: "Student",
    profilePic: "/profile.png",
  },
];
export default dummyUsers;
