const schoolAdmin = [
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",
    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",
    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    FirstName: "Doe",
    MiddleName: "John",
    LastName: "Peter",

    SchoolName: "Grace Academy",
    Designation: "Principal",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
];
export default schoolAdmin;
