const school = [
  {
    SchoolName: "Peace International College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Active",
    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "God's Grace College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Inactive",
    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "Peace International College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Active",

    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "Peace International College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Active",

    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "Peace International College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Active",

    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "God's Grace College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Inactive",
    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "God's Grace College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Inactive",
    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "Peace International College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Active",

    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
  {
    SchoolName: "Peace International College",
    SchoolType: "Private",
    ShortSchName: "PIC",
    RegDate: "13/02/2025",
    Status: "Active",

    EducationLevel: "Senior Sec. School",
    Phone: "08052835653",
    Email: "joedoe001@gmail.com",
    Address: "Abeokuta,Ogun State, Nigeria",
  },
];
export default school;
