const User = [
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },

  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
  {
    Surname: "Doe",
    FirstName: "John",
    PhoneNumber: "08118581710",
    EmailAddress: "joedoe001@gmail.com",
    UserRole: "School Admin",
    Address: "Abeokuta,Ogun State,Nigeria",
  },
];
export default User;
